### ISSUE TITLE
[gemmacoswindow]: failed to init GLEW: your system only supports openGL-1.0

### ISSUE THREAD

**Issue by sebshader** [umlaeute/Gem#257]
I get this error on osx 10.14.6 in 64 bit Pd 0.51.0, both compiled from master and downloaded via deken.

then there are a whole bunch of: "[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!"

my configure flags (using homebrew llvm/libomp):
`./configure --with-libvlc-CFLAGS=-I/Applications/VLC.app/Contents/MacOS/include --with-libvlc-LIBS="-L/Applications/VLC.app/Contents/MacOS/lib -lvlc" --with-pd=/Applications/Pd.app/Contents/Resources --without-QuickTime-framework --without-Carbon-framework --with-defaultwindow=gemmacoswindow --with-pd=/Applications/Pd-0.51-0-Next.app/Contents/Resources/src LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/lib" CPPFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1 -I/usr/local/include" --prefix=/Users/sebshader/Library/Pd/Gem`

(I also tried gemcocoawindow)
I notice that this has come up before in #204

**Comment by sebshader** [comment]
huh, when I create it in gemmacoswindow-help it works, but not in for instance cone-help using gemwin..

**Comment by jamshark70** [comment]
One student has recently encountered this error after a macOS system upgrade (I believe upgraded to Big Sur... which was rather foolish right before exams given the heightened compatibility requirements for audio software)... She had completed Gem-related homework before, but now is unable to open a Gem window, receiving the two error messages noted in this thread.

Is there any way forward?

**Comment by umlaeute** [comment]
@jamshark70 i don't really know, but she could try changing the windowing backend, by changing the `gemdefaultwindow.pd` abstraction in the Gem/-folder and replacing the `[gemmacoswindow]` (or whatever is there) to one of the other `gem*window` options installed on your system. (just look out for any externals (`.pd_darwin`,...) in the Gem/-folder that match the "gem*window" pattern).
possibly good choices are:
- `[gemglfw3window]`
- `[gemglutwindow]`

**Comment by celestialtomes** [comment]
changing to [gemglutwindow] works... ish.... I have a simple live input delay patch for my laptop's webcam feed but when i change the delay time Pd crashes

**Comment by jamshark70** [comment]
> i don't really know, but she could try changing the windowing backend, by changing the gemdefaultwindow.pd abstraction in the Gem/-folder and replacing the [gemmacoswindow] (or whatever is there) to one of the other gem*window options installed on your system.

Ok, I wrote this up for her and will wait for a reply back. Hope it works (though based on celestialtomes's comment, I'm not quite optimistic).

**Comment by Ant1r** [comment]
@celestialtomes your crash could be totally unrelated to the current issue (your variable delay could be buggy). If you don't change the delay time, does it still crash?

**Comment by celestialtomes** [comment]
no it it does not crash as long as i don't change delay time

**Comment by Ant1r** [comment]
So i'd say you've successfully solved (locally) the current issue. 

Your crash is another thing, so maybe you can ask help (and post your patch) elsewhere if you need, e.g in the Pd mailing list.

**Comment by sebshader** [comment]
turns out the "your system only supports openGL-1.0" part of this is wrong since in src/Base/GemContext.cpp it should be `if (GLEW_ERROR_GL_VERSION_10_ONLY` == err)` instead of just `if (GLOW_ERROR_GL_VERSION_10_ONLY)` around line 156 I think. (which will always evaluate true obviously)

**Comment by sebshader** [comment]
maybe the cocoa window isn't made before the context tries to access it?

**Comment by umlaeute** [comment]
could you try with `[gemglfw3window]`? (you need to have `glfw` installed before running `./configure`)

**Comment by sebshader** [comment]
@umlaeute so far that's working fine, except that if I open certain patches from the examples folder before opening a gemwin (like from another help file) it crashes pd. (without a crash log).. for instance 02.advanced/04.Fog.pd. Many examples open fine without having opened a gemwin though..

the window also can't be closed by clicking the close button but that's not too big of a deal.

**Comment by umlaeute** [comment]
> the window also can't be closed by clicking the close button but that's not too big of a deal.

that's actually a feature.
the `[gemwin]` object (well, the `[gemglfw3window]` object, really), emits a `[window destroy(` message, that you can use to trigger a `[destroy(` message to the object itself (if you actually want that).

**Comment by umlaeute** [comment]
the crash is weirder (but should probably be discussed in a separate ticket)

**Comment by seppog** [comment]
had the same problem on silicon mac m1 12.0.1, replacing [gemmacoswindow] with [gemglfw3window] helped after installing glfw with brew, did only test some examples, they work, despite getting error: [gemglfw3window]: Cocoa: Failed to retrieve display name.

**Comment by umlaeute** [comment]
i hope that you only get the error message once.

**Comment by umlaeute** [comment]
also it seems that this was fixed (by just not emitting the error mesage) in upstream:https://github.com/glfw/glfw/commit/6a8ade99c753be7511c866782ef4dde1ba92cedc

**Comment by seppog** [comment]
in opening Gem->examples-> 01.basic->01.redSqauare.pd 3 times, but that's it. I'm using glfw 3.3.5 , thats what brew installes on my machine and tells me its up to date

**Comment by namork** [comment]
dear all. i'm having troubles to get pd running on a m1 macbook. can somebody summarize what makes pd/gem work on those machines? 
i downloaded Pd 0.52.1, go to help/find externals online/tipe in gem and download the newest version. the iy go to "/Library/Pd/Gem/gemdefaultwindow.pd" and find this:

#N canvas 3 45 450 300 10;
#X obj 125 66 inlet;
#X obj 125 243 outlet;
#X obj 125 145 t a a;
#X obj 175 187 route bang;
#X obj 175 167 spigot;
#X obj 208 143 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 0
1;
#X obj 232 208 print gem\$0win;
#X obj 125 100 gemglutwindow;
#X connect 0 0 7 0;
#X connect 2 0 1 0;
#X connect 2 1 4 0;
#X connect 3 1 6 0;
#X connect 4 0 3 0;
#X connect 5 0 4 1;
#X connect 7 0 2 0;

should i change gemglutwindow to something else? do i have to recompile something and if so, where could i find instructions to do that (for somebody who hasn't done this on a mac)? 

thank you very very much for any help!

**Comment by seppog** [comment]
see the comments above how I got it to run on an M1

**Comment by namork** [comment]
seppong. thanks a lot! i replaced gemlutwindow with gemglfw3window in gemdefaultwindow.pd after installing glfw 3.3.6 with brew (brew install glfw). but still get the message "[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!" what's wrong with me ;o) i must admit that i'm a user of pd and not good programmer...

**Comment by umlaeute** [comment]
make sure to restart Pd.

if the problem persists, you might have multiple copies on your system, and modify the wrong one :-) if this is the case, start Pd in "verbose" mode (<kbd>Preferences</kbd>-><kbd>Path</kbd>, check the `verbose` checkbox; restart) to see where Gem is actually loaded from, and us the `gemdefaultwindow.pd` that resides besides Gem.

or just:
1. create a new patch with a `[gemwin]` object
2. open the `[gemwin]` object (it's an abstraction)
3. find the `[pd window]` object (somewhere in the middle of the patch)
4. open the `[pd window]` object (it's a subpatch)
5. find the `[gemdefaultwindow]` object (somewhere in the middle of the patch)
6. open the `[gemdefaultwindow]` object (it's an abstraction)
7. find the `[gemmacoswindow]` object
8. **replace** it with a `[gemglfw3window]` object
9. *save* the *gemdefaultwindow.pd* abstraction
10. restart Pd & happily live after

**Comment by namork** [comment]
umlaut

wow. thank you very much! but i’m still too
stupid. i get the following message with this
preferences (and i changed the default in both
of the gems). 

looks like i can't be helped ;o(

sonnige grüsse, roman 





/Library/Pd/Gem/Gem.d_fat: dlopen(/Library/Pd/Gem/Gem.d_fat, 0x000A): tried: '/Library/Pd/Gem/Gem.d_fat' (fat file, but missing compatible architecture (have 'unknown,i386', need 'x86_64')), '/usr/lib/Gem.d_fat' (no such file)
GEM: Graphics Environment for Multimedia
GEM: ver: 0.94.git v0.94
GEM: compiled  on Feb 12 2019
GEM: maintained by IOhannes m zmoelnig
GEM: Authors :	Mark Danks (original version)
GEM:		Chris Clepper
GEM:		Cyrille Henry
GEM:		IOhannes m zmoelnig
GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
GEM: found a bug? miss a feature? please report it:
GEM: 	homepage https://gem.iem.at/
GEM: 	bug-tracker https://bugs.gem.iem.at/
GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
GEM: compiled for MMX/SSE2 architecture
GEM: using SSE2 optimization
GEM: detected 10 CPUs
GEM: image loading plugins: magick SGI STB imageIO jpeg tiff
GEM: film loading plugins: AVF quicktime4linux
GEM: image saving plugins: SGI STB imageIO jpeg magick tiff
GEM: model loading plugins: ASSIMP3 OBJ
GEM: video record plugins: QT4L
GEM: video capture plugins: AVF decklink
 sigmund~ -npts 8192 -hop 2048 -npeak 36 peaks
... couldn't create
/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 0x000A): Library not loaded: @loader_path/libglfw.3.dylib
  Referenced from: /Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin
  Reason: tried: '/Users/romankeller/Documents/Pd/externals/Gem/libglfw.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libglfw.3.dylib' (no such file)
/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 0x000A): Library not loaded: @loader_path/libglfw.3.dylib
  Referenced from: /Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin
  Reason: tried: '/Users/romankeller/Documents/Pd/externals/Gem/libglfw.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libglfw.3.dylib' (no such file)
/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 0x000A): Library not loaded: @loader_path/libglfw.3.dylib
  Referenced from: /Users/romankeller/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin
  Reason: tried: '/Users/romankeller/Documents/Pd/externals/Gem/libglfw.3.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libglfw.3.dylib' (no such file)
 gemglfw3window
... couldn't create
[pix_texture]: using mode 1: TEXTURE_RECTANGLE
err-corr: no such object 

------------------------------------------------
atelier roman keller
lutherstr. 30 | ch-8004 zürich
+41 44 291 53 45 | +41 79 69 19 836
***@***.***
------------------------------------------------

**Comment by umlaeute** [comment]
aye. we are getting somewhere...

it seems you do have two concurrent installations of Gem: one in `/Library/Pd/Gem/`, the other in `/Users/romankeller/Documents/Pd/externals/Gem/`.
and you end up using the one in `/Users/romankeller/Documents/Pd/externals/Gem/` (as you should).

now the problem is, that you have an architecture mismatch: the `libglfw.3.dylib` seems to be compiled for the M1 (`arm64`), but Gem is compiled for `x86_64`, and you cannot load an arm-binary into an intel-process (and vice-versa). that's a general limitations of cross-architecture library loading on all OSs i know of.

now, the `libglfw.3.dylib` that ships with Gem is not used for whatever reasons
afaict, this also happened to @seppog , so he installed glfw3 via brew.

however, in seppo's case, (i guess) he got an x86_64-version of glfw3 (via brew), which worked;
whereas you got the library for your native architecture (arm64).

so: @seppog how did you manage to get the x86_64 version?
(it might be a matter of timing: e.g. installing the brew-package when there were only x86_64 pre-compiled packages available; and now there are arm64 binaries available as well).
i don't know if it's possible to force brew into downloading an older version...

**Comment by seppog** [comment]
to be honest, I don't know, installed glfw3 dec 21 but did upgrade my brew install just recently. Brew info glfw shows:
glfw: stable 3.3.6 (bottled), HEAD
Multi-platform library for OpenGL applications
https://www.glfw.org/
/opt/homebrew/Cellar/glfw/3.3.6 (14 files, 475.8KB) *
  Poured from bottle on 2021-12-20 at 22:31:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glfw.rb

**Comment by namork** [comment]
> Am 28.02.2022 um 11:15 schrieb umläute ***@***.***>:
> 
> 
> aye. we are getting somewhere...
> 
> it seems you do have two concurrent installations of Gem: one in /Library/Pd/Gem/, the other in /Users/romankeller/Documents/Pd/externals/Gem/.
> and you end up using the one in /Users/romankeller/Documents/Pd/externals/Gem/ (as you should).
> 
> 
thanks for telling me. i deleted the gem in /Library/PD...

> now the problem is, that you have an architecture mismatch: the libglfw.3.dylib seems to be compiled for the M1 (arm64), but Gem is compiled for x86_64, and you cannot load an arm-binary into an intel-process (and vice-versa). that's a general limitations of cross-architecture library loading on all OSs i know of.
> 
> now, the libglfw.3.dylib that ships with Gem is not used for whatever reasons
> afaict, this also happened to @seppog <https://github.com/seppog> , so he installed glfw3 via brew.
> 
> however, in seppo's case, (i guess) he got an x86_64-version of glfw3 (via brew), which worked;
> whereas you got the library for your native architecture (arm64).
> 
> so: @seppog <https://github.com/seppog> how did you manage to get the x86_64 version?
> (it might be a matter of timing: e.g. installing the brew-package when there were only x86_64 pre-compiled packages available; and now there are arm64 binaries available as well).
> i don't know if it's possible to force brew into downloading an older version…
> 
maybe i have to wait until gem ships in arm64 then ;o(

**Comment by namork** [comment]
does this website suggest glfw to be for both plattforms?

https://formulae.brew.sh/formula/glfw

when i download the precompiled version i can select the architecture by only copying the subsequent files. 

but unfortunately i don't know where to put them ;o(

https://www.glfw.org/download.html

**Comment by umlaeute** [comment]
this is **totally untested**, but there's some experimental universal builds (x86_64 + amd64) available at [our CI](https://git.iem.at/pd/Gem/-/jobs/artifacts/develop/download?job=macOS).

**Comment by namork** [comment]
dear umläute

i’m unable again. the link ends at 404 on my browser.

https://git.iem.at/pd/Gem/-/jobs/artifacts/develop/download?job=macOS <https://git.iem.at/pd/Gem/-/jobs/artifacts/develop/download?job=macOS>

and i can’t find it here;

https://git.iem.at/pd/Gem/-/jobs <https://git.iem.at/pd/Gem/-/jobs>

sunny greetings, roman

**Comment by umlaeute** [comment]
sorry, i pasted the wrong link: https://git.iem.at/pd/Gem/-/jobs/artifacts/master/download?job=Darwin_snapshot

afaict, this includes universal binaries for all Gem stuff, but not for any helper libraries.
(so for (advanced) model-loading, and image-reading you might need to install additional libraries via `brew` as well; `glfw` you already have...)

**Comment by 60-hz** [comment]
Still cannot run Gem properly with M1 Mac with Monterey and the universal version from the link. Still the same problem:
- Need to change the default windows to [gemglfw3window] to be able to create a window
- The buffer is displayed in the lower left quarter of the screen
Tried with pd-0.52-2 Universal with Rosetta2 compatibility.

Without Rosetta2, got:

```
/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'
/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'
```

**Comment by megrimm** [comment]
hello,

where do I find the experimental amr64 build? link above is dead.

tried my own build but still getting assimp errors here:
https://github.com/umlaeute/Gem/issues/288

thanks!

**Comment by umlaeute** [comment]
true enough.

i've dropped the `Darwin_snapshot` builds, and with some recent builds the macOS job failed (but others succeeded), which seems to have removed the artifact.

in any case, i think i've managed to fix it again. the new download URL is:

https://git.iem.at/pd/Gem/-/jobs/artifacts/master/download?job=Darwin

**Comment by Bartlebooth1424** [comment]
> Still cannot run Gem properly with M1 Mac with Monterey and the universal version from the link. Still the same problem:
> 
> * Need to change the default windows to [gemglfw3window] to be able to create a window
> * The buffer is displayed in the lower left quarter of the screen
>   Tried with pd-0.52-2 Universal with Rosetta2 compatibility.
> 
> Without Rosetta2, got:
> 
> ```
> /Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'
> /Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'
> ```

I wanted to add that I am reproducing these same two errors running on a late 2013 Intel i5 machine (Mojave - 10.14.6). I can only produce a render window through switching the renderer and even then the image is pinned to the bottom-left quarter of the render window. Attempts to correct this with offset messages to the gemwin object have not been successful.

**Comment by umlaeute** [comment]
the "bottom-left quarter" would be https://github.com/umlaeute/Gem/issues/243 which should be fixed in current `master` (but then there is also https://github.com/umlaeute/Gem/issues/342 which indicates that something went wrong again...)

**Comment by ben-wes** [comment]
just tried the latest build on my M2 mac with the latest Pd master build and the latest artifact from https://git.iem.at/pd/Gem/-/jobs/48964 and also get the `symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'` error.

this doesn't really add much to the ticket here - but i'll happily help testing at least.
i had a working Gem version running here which i built locally a few weeks ago (although unfortunately, i can't reproduce this anymore and don't know what i did there exactly). but i wanted to update with the latest changes since fullscreen mode didn't work for me.

**Comment by cecisoloaga** [comment]
Im using Monterey 12.6 on an intel Mac. Pure data 0.54. I change the name of the did the installations recommended in deken Gem, libdir, pmpd. I installed homebrew to install glfw library. restarted PD several times. I can not open the Gem window in PD.
This is the log i get:

----------------- done with main ----------------------
connection from 'pd' to 'pd-gui' on 127.0.0.1:51670
Tk 8.6.12
detected font: DejaVu Sans Mono
using font: Menlo normal
Loading plugin: /Applications/Pd-0.54-0.app/Contents/Resources/Scripts/pd_deken.tcl
[deken] Platform detected: Darwin-amd64-float32
Loading plugin: /Applications/Pd-0.54-0.app/Contents/Resources/Scripts/pd_docsdir.tcl
Pd documents directory: /Users/ceciliasoloaga/Documents/Pd
GEM: Graphics Environment for Multimedia
GEM: ver: 0.94.git v0.94-689-g6da25e8e1
GEM: compiled  on Sep  1 2023
GEM: maintained by IOhannes m zmoelnig
GEM: Authors :	Mark Danks (original version)
GEM:		Chris Clepper
GEM:		Cyrille Henry
GEM:		IOhannes m zmoelnig
GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
GEM: found a bug? miss a feature? please report it:
GEM: 	homepage https://gem.iem.at/
GEM: 	bug-tracker https://bugs.gem.iem.at/
GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
GEM: compiled for MMX/SSE2 architecture
GEM: using SSE2 optimization
GEM: detected 12 CPUs
GEM: image loading plugins: SGI STB imageIO jpeg
GEM: film loading plugins: AVF
GEM: image saving plugins: SGI STB imageIO jpeg
GEM: model loading plugins: ASSIMP3 OBJ
GEM: video record plugins: NDI PNM
GEM: video capture plugins: AVF NDI decklink
/Users/ceciliasoloaga/Documents/Pd/externals/libdir/libdir.pd_darwin:dlopen(/Users/ceciliasoloaga/Documents/Pd/externals/libdir/libdir.pd_darwin, 0x000A): symbol not found in flat namespace (_sys_helppath)
libdir: can't load library
pmpd: can't load library
-lib libdir: can't load library

--------------------------------------------------------------------
:: Cyclone 0.7-0; Released february 21st 2023
:: License: BSD-3-Clause (aka Revised BSD License)
:: Copyright © 2003-2021 - Krzysztof Czaja, Hans-Christoph Steiner,
:: Fred Jan Kraan, Alexandre Porres, Derek Kwan, Matt Barber
:: and others.
:: -----------------------------------------------------------------
:: Cyclone 0.7-0 needs at least Pd 0.53-2
::   (you have 0.54-0, you're good!)
:: Loading the cyclone library loaded non alphanumeric objects,
:: which are: [!-], [!-~], [!/], [!/~], [!=~], [%~], [+=~],
:: [<=~], [<~], [==~], [>=~] and [>~]
:: NOTE: Loading this binary did not load the path
:: you need to add 'cyclone' to the "preferences=>path"
:: or use [declare -path cyclone] (this guarantees search priority)
--------------------------------------------------------------------


	♡♡♡
	♡ the zexy external  2.4.2
	♡ (c) 1999-2023 IOhannes m zmölnig
	♡       forum::für::umläute
	♡       iem  @  kug
	♡  compiled  Jul  7 2023
	♡ send me a 'help' message
	♡♡♡

matchbox: OSC-pattern matching code (c) Matt Wright, CNMAT
Darwin: can't load library
the Pd window filtered 94 lines

**Comment by umlaeute** [comment]
@cecisoloaga there's no Gem-related error in your output.

**Comment by umlaeute** [comment]
i think this has been resolved.
